const days=[
{n:1,date:'Mardi 1er septembre 2026',title:'Arrivée à Lyon',spirit:'Arriver, récupérer les vélos et s’installer sans se presser.',facts:[['Transport','Rhônexpress'],['Hébergement','56, rue Baraban'],['Priorité','Remonter les vélos'],['Rythme','Journée légère']],stops:[['Aéroport Lyon–Saint-Exupéry','Récupérer les bagages et les boîtes de vélo.'],['Rhônexpress','Rejoindre Lyon Part-Dieu en environ 30 minutes.'],['Airbnb','Marcher jusqu’au 56, rue Baraban, puis s’installer.'],['Soirée','Remonter les vélos, recharger les appareils et prendre un repas simple.']]},
{n:2,date:'Mercredi 2 septembre 2026',title:'Découverte de Lyon',spirit:'Découvrir Lyon à pied, entre patrimoine, gastronomie et quartiers historiques.',facts:[['Départ','08 h 30'],['Marche','Journée urbaine'],['Budget repas','50 à 70 € pour deux'],['Retour','Vers 17 h 45']],stops:[['08 h 30 — Gare Part-Dieu','Acheter les billets Lyon → Strasbourg et confirmer les deux emplacements vélo.'],['09 h 15 — Vieux-Lyon','Rues Saint-Jean et du Bœuf, traboules et façades Renaissance.'],['11 h 30 — Pause gourmande','Brioche ou tarte aux pralines dans une pâtisserie artisanale.'],['12 h 15 — Place Bellecour','Pause et vue vers Fourvière.'],['13 h 00 — Halles Paul Bocuse','Composer un repas avec rosette, Saint-Marcellin, pain et pâtisserie.'],['15 h 30 — Presqu’île','Places des Jacobins et des Terreaux, rue de la République et Fresque des Lyonnais.']]},
{n:3,date:'Jeudi 3 septembre 2026',title:'Lyon → Strasbourg',spirit:'Transformer le trajet en train en une transition douce vers le début du voyage.',facts:[['Transport','Train avec 2 vélos'],['Arrivée','Strasbourg'],['Hébergement','17, rue des Orfèvres'],['Statut','Horaire à confirmer']],stops:[['Avant le départ','Prévoir de l’eau et des collations.'],['Gare Lyon Part-Dieu','Arriver tôt pour repérer la voiture vélo et installer les bicyclettes.'],['Strasbourg','Rejoindre l’hébergement et effectuer une première promenade légère.']]},
{n:4,date:'Vendredi 4 septembre 2026',title:'Découverte de Strasbourg',spirit:'Prendre le pouls de l’Alsace avant de donner le premier coup de pédale.',facts:[['Quartiers','Grande Île et Petite France'],['Hébergement','17, rue des Orfèvres'],['Rythme','À pied'],['Veille du départ','Préparer les sacoches']],stops:[['Cathédrale Notre-Dame','Découvrir la façade, l’intérieur et le secteur de la place de la Cathédrale.'],['Petite France','Canaux, maisons à colombages et ponts couverts.'],['Barrage Vauban','Profiter de la terrasse panoramique lorsqu’elle est accessible.'],['Marché ou commerces locaux','Acheter le souper et les provisions pour la première étape.'],['Soirée','Préparer les vélos, vérifier la météo et charger les appareils.']]},
...Array.from({length:23},(_,i)=>({n:i+5,date:`${i+5} septembre 2026`,title:i===0?'Grand départ — Strasbourg':i===22?'Arrivée à Sète':'Étape vélo à préciser',pending:true,spirit:i===0?'Quitter Strasbourg et laisser le voyage commencer.':i===22?'Atteindre la Méditerranée et savourer le chemin parcouru.':'Cette étape sera complétée lorsque le découpage définitif sera confirmé.',facts:[['Parcours','RideWithGPS'],['Distance','À confirmer'],['Hébergement','À ajouter'],['Repas','Marché ou option locale']],stops:[['Planification','Le détail de cette journée n’est pas encore confirmé. Utiliser le parcours maître RideWithGPS comme référence.']]}))];
function route(){const id=(location.hash||'#accueil').slice(1).split('?')[0];document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));(document.getElementById(id)||document.getElementById('accueil')).classList.add('active');window.scrollTo(0,0)}
function renderDays(){dayList.innerHTML=days.map(d=>`<div class="dayitem ${d.pending?'pending':''}" data-day="${d.n}"><div class="daynum">${d.n}</div><div><b>${d.title}</b><small>${d.date}${d.pending?' · à compléter':''}</small></div></div>`).join('');dayList.onclick=e=>{const x=e.target.closest('[data-day]');if(x){renderDay(+x.dataset.day);location.hash='day'}}}
function renderDay(n){const d=days.find(x=>x.n===n);dayContent.innerHTML=`<p class="eyebrow">JOUR ${d.n}</p><h1>${d.title}</h1><p class="muted">${d.date}</p>${d.pending?'<div class="panel warning"><b>Étape provisoire</b><p>Le découpage, la distance et l’hébergement restent à confirmer.</p></div>':''}<div class="spirit"><small>L’ESPRIT DE LA JOURNÉE</small><strong>${d.spirit}</strong></div><div class="facts">${d.facts.map(f=>`<div class="fact"><small>${f[0]}</small><b>${f[1]}</b></div>`).join('')}</div><h2>Programme</h2><div class="timeline">${d.stops.map(s=>`<div class="stop"><b>${s[0]}</b><p>${s[1]}</p></div>`).join('')}</div>${d.n>=5?'<a class="btn" target="_blank" href="https://ridewithgps.com/routes/53578421?privacy_code=kkxuelJLVp05PTeBOPnZdw6jLSiA1Exd">Ouvrir RideWithGPS</a>':''}`}
function loadNotes(){const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');notes.innerHTML=a.map((n,i)=>`<div class="noteitem"><button data-del="${i}">Supprimer</button><b>${escapeHtml(n.t)}</b><p>${escapeHtml(n.x).replace(/\n/g,'<br>')}</p></div>`).join('')||'<p class="muted">Aucune note enregistrée.</p>'}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
saveNote.onclick=()=>{if(!noteText.value.trim())return;const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');a.unshift({t:noteTitle.value.trim()||new Date().toLocaleDateString('fr-CA'),x:noteText.value.trim()});localStorage.setItem('france2026notes',JSON.stringify(a));noteTitle.value=noteText.value='';loadNotes()};notes.onclick=e=>{if(e.target.dataset.del!==undefined){const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');a.splice(+e.target.dataset.del,1);localStorage.setItem('france2026notes',JSON.stringify(a));loadNotes()}};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);window.addEventListener('hashchange',route);renderDays();loadNotes();route();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
