const days=[
{n:1,date:'Mardi 1er septembre 2026',title:'Arrivée à Lyon',spirit:'Arriver, récupérer les vélos et s’installer tranquillement avant de commencer le voyage.',facts:[['Transport','Rhônexpress'],['Hébergement','14, rue Saint-Victorien'],['Priorité','Remonter les vélos'],['Rythme','Journée légère']],stops:[
['Aéroport Lyon–Saint-Exupéry','Récupérer les bagages et les deux vélos, puis rejoindre la station Rhônexpress.'],
['Rhônexpress → Lyon Part-Dieu','Prendre le Rhônexpress jusqu’à Lyon Part-Dieu. Le trajet dure environ 30 minutes. Les départs sont fréquents en journée.',[['🎟️ Billets Rhônexpress','https://www.rhonexpress.fr/'],['📍 Gare Lyon Part-Dieu','https://wego.here.com/search/Gare%20Lyon%20Part-Dieu']]],
['Gare Part-Dieu → Airbnb','Rejoindre l’Airbnb au 14, rue Saint-Victorien, 69003 Lyon, avec les vélos et les bagages.',[['🏡 Ouvrir l’Airbnb dans HERE WeGo','https://wego.here.com/search/14%20Rue%20Saint-Victorien%2069003%20Lyon']]],
['Installation et vélos','S’installer, remonter les deux vélos, vérifier les freins, les changements de vitesse et la pression des pneus, puis remettre en place les sacs de vélo. Recharger les GPS, téléphones et batteries externes.'],
['Sacs de transport','Conserver les sacs de transport à l’Airbnb pendant les deux premières nuits. L’entreposage pour la durée du circuit sera réglé une fois sur place à Lyon, probablement avec la consigne Bounce près de la gare Part-Dieu.'],
['Souper et soirée','Prévoir un repas simple près de l’Airbnb ou à emporter. L’objectif est de récupérer du vol et de terminer tranquillement la préparation des vélos.'],
['Avant de dormir','Faire une dernière vérification des vélos, recharger le matériel électronique, vérifier la météo et préparer la journée de visite de Lyon du lendemain.']
],links:[['🏡 Airbnb — 14 rue Saint-Victorien','https://wego.here.com/search/14%20Rue%20Saint-Victorien%2069003%20Lyon'],['🚆 Gare Lyon Part-Dieu','https://wego.here.com/search/Gare%20Lyon%20Part-Dieu'],['🎟️ Rhônexpress','https://www.rhonexpress.fr/']]},
{n:2,date:'Mercredi 2 septembre 2026',title:'Découverte de Lyon',spirit:'Régler d’abord les deux points pratiques essentiels, puis découvrir Lyon librement, sans horaire imposé.',facts:[['Priorité 1','Billets Lyon → Strasbourg'],['Priorité 2','Entreposage des sacs de vélo'],['Déplacement','À pied et en transport urbain'],['Rythme','Libre après les priorités']],stops:[
['1. Priorité — Régler les billets de train','Acheter et confirmer les billets Lyon → Strasbourg pour le 3 septembre, avec le transport des deux vélos. Vérifier les horaires, les correspondances et les modalités vélo avant de poursuivre la journée.',[['🚆 SNCF Connect','https://www.sncf-connect.com/'],['📍 Gare Lyon Part-Dieu','https://wego.here.com/search/Gare%20Lyon%20Part-Dieu']]],
['2. Priorité — Régler les bagages','Finaliser l’entreposage des sacs de transport des vélos pour la durée du circuit. La solution privilégiée est la consigne Bounce près de Lyon Part-Dieu. Si cette question est déjà réglée avant le 2 septembre, cette étape pourra simplement être retirée lors de la prochaine mise à jour.',[['🧳 Bounce — Lyon Part-Dieu','https://bounce.com/city/lyon/lyon-part-dieu'],['📍 Gare Lyon Part-Dieu','https://wego.here.com/search/Gare%20Lyon%20Part-Dieu']]],
['Vieux-Lyon','Quartier Renaissance aux ruelles pavées, cours intérieures et traboules. Une belle introduction à l’histoire et à l’ambiance de Lyon.<br><strong>⏱️ Durée suggérée :</strong> 1 h 30 à 2 h.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Vieux-Lyon%2C%20Lyon'],['📖 En savoir plus','https://www.visiterlyon.com/decouvrir/les-quartiers-de-lyon/le-vieux-lyon']]],
['Fourvière et son belvédère','Le belvédère offre l’un des meilleurs panoramas sur la ville. La visite intérieure de la basilique demeure facultative selon votre envie.<br><strong>⏱️ Durée suggérée :</strong> 45 à 60 min.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Basilique%20Notre-Dame%20de%20Fourvi%C3%A8re%2C%20Lyon'],['📖 En savoir plus','https://www.fourviere.org/']]],
['Presqu’île et places centrales','Promenade urbaine entre la place Bellecour, les rues commerçantes, les façades historiques et les quais du Rhône et de la Saône.<br><strong>⏱️ Durée suggérée :</strong> 1 h 30 à 2 h.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Place%20Bellecour%2C%20Lyon'],['📖 En savoir plus','https://www.visiterlyon.com/decouvrir/les-quartiers-de-lyon/la-presqu-ile']]],
['Halles Paul Bocuse','Marché couvert emblématique pour découvrir les spécialités lyonnaises, grignoter sur place ou acheter un repas simple à emporter.<br><strong>⏱️ Durée suggérée :</strong> 1 h à 1 h 30.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Halles%20de%20Lyon%20Paul%20Bocuse'],['📖 En savoir plus','https://www.halles-de-lyon-paulbocuse.com/']]],
['Parc de la Tête d’Or','Grande pause verte avec lac, jardins et longues allées. Une option agréable pour ralentir le rythme après les quartiers centraux.<br><strong>⏱️ Durée suggérée :</strong> 1 h à 2 h.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Parc%20de%20la%20T%C3%AAte%20d%27Or%2C%20Lyon'],['📖 En savoir plus','https://www.lyon.fr/lieu/parcs/parc-de-la-tete-dor']]]
]},
{n:3,date:'Jeudi 3 septembre 2026',title:'Lyon → Strasbourg',spirit:'Transformer le trajet en train en une transition douce vers le début du voyage.',facts:[['Transport','Train avec 2 vélos'],['Arrivée','Gare de Strasbourg'],['Hébergement','17, rue des Orfèvres'],['Statut','Horaire à confirmer']],stops:[['Résumé','7 h 26 • 3 TER • 2 correspondances • Vélo sans réservation'],['⚠️ À confirmer','Horaires et numéros de train à confirmer lors de l’achat des billets SNCF.'],['Avant le départ','Prévoir de l’eau et des collations.'],['Gare Lyon Part-Dieu','Arriver tôt pour repérer la voiture vélo et installer les bicyclettes.'],['Gare de Strasbourg → Airbnb','Rejoindre le 17, rue des Orfèvres à vélo.'],['Installation','Déposer les bagages et sécuriser les vélos.']],links:[['GPX - Strasbourg @ Strasbourg','https://ridewithgps.com/routes/56200417?privacy_code=fHM29CvZ3sIqPWAitvokEywHJS8kqvcn'],['🗺️ Voir le trajet dans HERE WeGo','https://wego.here.com/directions/mix/Gare%20de%20Strasbourg%2C%20Strasbourg/17%20Rue%20des%20Orf%C3%A8vres%2C%2067000%20Strasbourg'],['🚆 SNCF Connect','https://www.sncf-connect.com/'],['🚲 Vélo à bord','https://www.veloabord.fr']]},
{n:4,date:'Vendredi 4 septembre 2026',title:'Découverte de Strasbourg',spirit:'Découvrir Strasbourg avant le grand départ.',facts:[['Type','Journée de visite'],['Hébergement','17, rue des Orfèvres'],['Rythme','Libre'],['Départ vélo','Le lendemain']],stops:[
['Cathédrale Notre-Dame','Chef-d’œuvre gothique en grès rose, célèbre pour sa façade sculptée, ses vitraux et son horloge astronomique. La visite intérieure demeure facultative selon votre intérêt.<br><strong>⏱️ Durée suggérée :</strong> 45 à 60 min.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Cath%C3%A9drale%20Notre-Dame%20de%20Strasbourg'],['🧭 Ouvrir dans HERE WeGo','https://share.here.com/l/48.5817,7.750565,Cath%C3%A9drale%20Notre-Dame%20de%20Strasbourg?z=17'],['📖 En savoir plus','https://www.visitstrasbourg.fr/decouvrir-strasbourg/les-incontournables/la-cathedrale/']]],
['Petite France','Quartier emblématique autour des canaux de l’Ill, avec ses maisons à colombages, ses ponts et ses anciennes rues de tanneurs. C’est l’un des meilleurs secteurs pour flâner sans itinéraire rigide.<br><strong>⏱️ Durée suggérée :</strong> 1 h à 1 h 30.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Petite%20France%2C%20Strasbourg'],['🧭 Ouvrir dans HERE WeGo','https://share.here.com/l/48.580923,7.74063,Petite%20France%20Strasbourg?z=16'],['📖 En savoir plus','https://www.visitstrasbourg.fr/decouvrir-strasbourg/les-incontournables/la-petite-france/']]],
['Barrage Vauban','Ancien ouvrage défensif construit à la fin du XVIIe siècle. Sa terrasse panoramique offre une vue remarquable sur les Ponts Couverts, la Petite France et la cathédrale.<br><strong>⏱️ Durée suggérée :</strong> 30 à 45 min.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Barrage%20Vauban%2C%20Strasbourg'],['🧭 Ouvrir dans HERE WeGo','https://share.here.com/l/48.57944,7.73806,Barrage%20Vauban%20Strasbourg?z=17'],['📖 En savoir plus','https://www.visitstrasbourg.fr/decouvrir-strasbourg/les-incontournables/la-petite-france/']]],
['Quartier européen','Secteur moderne regroupant le Parlement européen, le Conseil de l’Europe et la Cour européenne des droits de l’homme. L’option à vélo permet d’y aller facilement depuis le centre.<br><strong>⏱️ Durée suggérée :</strong> 1 h à 1 h 30.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Parlement%20europ%C3%A9en%2C%20Strasbourg'],['🧭 Ouvrir dans HERE WeGo','https://share.here.com/l/48.59702,7.76929,Parlement%20europ%C3%A9en%20Strasbourg?z=16'],['📖 En savoir plus','https://www.visitstrasbourg.fr/decouvrir-strasbourg/les-incontournables/le-quartier-europeen/']]],
['💡 Conseil d’Alice','La veille, ouvrez les liens « En savoir plus » des deux ou trois visites qui vous attirent le plus. Quelques minutes de lecture suffiront pour mieux apprécier les lieux le lendemain.']
]},
{n:5,date:'Samedi 5 septembre 2026',title:'Strasbourg → Barr',spirit:'Première vraie journée à vélo : prendre le rythme et profiter des villages alsaciens sans se presser.',facts:[['Distance','48 km'],['Dénivelé positif','356 m'],['Pause déjeuner possible','Molsheim ou Rosheim'],['Arrivée','Barr']],stops:[['Départ — Airbnb de Strasbourg','Départ directement du 17, rue des Orfèvres.'],['Route des Vins d’Alsace','Rouler tranquillement vers le sud en suivant le nouveau parcours jusqu’à Barr.'],['Molsheim','Première possibilité de pause boulangerie ou pâtisserie en cours de route.'],['Rosheim','Autre halte intéressante avant de poursuivre vers Barr.'],['Arrivée — Barr','Le nouveau GPX se termine à Barr.'],['Hébergement','Réservation à Barr à confirmer.'],['🍽️ Repas à proximité','À Barr, vous aurez plusieurs options pour le repas du soir, dont Restaurant Au Potin et Le M, ainsi que des solutions à emporter.'],['🛒 Provisions','Carrefour Contact est pratique pour acheter le repas du soir ou les provisions du lendemain.'],['🥐 Boulangerie','Boulangerie Pâtisserie Le Piémont est une option pratique à Barr.'],['⭐ À ne pas manquer','Profitez du centre de Barr et de son ambiance de petite ville viticole après avoir rangé les vélos.']],links:[['GPX - Strasbourg @ Barr','https://ridewithgps.com/routes/56990566'],['🏡 Demander à Alice de trouver un hébergement','https://chatgpt.com/'],['🥐 Boulangerie Pâtisserie LR — Molsheim','https://share.here.com/l/48.5417272,7.4917216,Boulangerie%20P%C3%A2tisserie%20LR%20-%2030%20place%20de%20l%27H%C3%B4tel%20de%20Ville%2C%20Molsheim?z=18'],['🥐 Boulangerie Rohmer — Rosheim','https://share.here.com/l/48.4964241,7.4705185,Boulangerie%20P%C3%A2tisserie%20Rohmer%20-%20104%20rue%20du%20G%C3%A9n%C3%A9ral%20de%20Gaulle%2C%20Rosheim?z=18'],['🥡 Repas à emporter — Barr','https://wego.here.com/search/restaurant%20%C3%A0%20emporter%20Barr%20France'],['📍 Centre de Barr dans HERE WeGo','https://wego.here.com/search/Barr%2067140%20France'],['🥐 Le Piémont — Barr','https://share.here.com/l/48.407034,7.450943,Boulangerie%20P%C3%A2tisserie%20Le%20Pi%C3%A9mont%20-%2032%20Grand%20Rue%2C%20Barr?z=18'],['🛒 Provisions — Barr','https://wego.here.com/search/Carrefour%20Contact%20Barr']]},
{n:6,date:'Dimanche 6 septembre 2026',title:'Barr → Colmar',spirit:'Suivre la Route des Vins à votre rythme en profitant des villages viticoles et des paysages d’Alsace.',facts:[['Distance','48 km'],['Dénivelé positif','322 m'],['Pause déjeuner principale','Châtenois — vers km 21'],['Arrivée','Centre de Colmar']],stops:[['Départ — Barr','Départ de Barr pour une étape de 48 km vers Colmar.'],['🥐 Pause matinale — Dambach-la-Ville','Vers le km 13. La Pâtisserie Kamm, 85 rue du Maréchal Foch, se trouve à environ 190 m du tracé GPX. Elle est ouverte le dimanche matin; c’est une halte très facile sans véritable détour.'],['🥐 Déjeuner conseillé — Châtenois','Vers le km 21. La Boulangerie-Pâtisserie Christian, 61 rue du Maréchal Foch, est pratiquement sur le parcours : le tracé GPX passe à environ 10 m. Elle est ouverte le dimanche de 7 h à 12 h.'],['🍽️ Repas à proximité','À Colmar, recherchez les restaurants, traiteurs et pizzerias offrant des plats à emporter près du centre historique.'],['🛒 Épicerie / marché','Le Marché couvert et les commerces du centre sont pratiques pour acheter un repas simple ou les provisions du lendemain.'],['⭐ À ne pas manquer','Mittelbergheim, Dambach-la-Ville, Châtenois, les paysages de la Route des Vins et le centre historique de Colmar.']],links:[['GPX - Barr @ Colmar','https://ridewithgps.com/routes/56138400'],['🏡 Demander à Alice de trouver un Airbnb','https://chatgpt.com/'],['🥐 Pâtisserie Kamm — Dambach-la-Ville (~ km 13)','https://share.here.com/l/48.3255828,7.4250533,Patisserie%20Kamm%20-%2085%20Rue%20du%20Marechal%20Foch%2C%20Dambach-la-Ville?z=18'],['🥐 Boulangerie-Pâtisserie Christian — Châtenois (~ km 21)','https://share.here.com/l/48.2725431,7.3992092,Boulangerie-Patisserie%20Christian%20-%2061%20Rue%20du%20Marechal%20Foch%2C%20Chatenois?z=18'],['🥡 Repas à emporter — Colmar centre','https://wego.here.com/search/restaurant%20%C3%A0%20emporter%20centre%20Colmar'],['🛒 Marché couvert de Colmar','https://wego.here.com/search/March%C3%A9%20couvert%20de%20Colmar'],['📍 Centre de Colmar','https://wego.here.com/search/centre%20historique%20Colmar']]},
{n:7,date:'Lundi 7 septembre 2026',title:'Colmar → Cernay',spirit:'Poursuivre vers le sud sur une étape plus courte, avec une vraie pause gourmande à Rouffach avant l’arrivée à Cernay.',facts:[['Distance','54 km'],['Dénivelé positif','442 m'],['Pause pâtisserie','Rouffach — vers le km 20'],['Arrivée','Cernay']],stops:[
['Départ — Colmar','Quitter Colmar en suivant le nouveau tracé GPX vers Rouffach, puis poursuivre jusqu’à Cernay.'],
['🥐 Pause pâtisserie — Rouffach','Vers le km 20. La Boulangerie-Pâtisserie Astrid et Alexandre HADEY, 13 rue de la Prévoté, est ouverte le lundi de 5 h 30 à 13 h puis de 15 h 30 à 18 h 30. Le parcours traverse le centre de Rouffach : c’est la halte principale recommandée demain.'],
['⭐ Rouffach','Charmante cité viticole aux rues anciennes et aux maisons alsaciennes traditionnelles.<br><strong>⏱️ Durée suggérée :</strong> 20 min.',[['📍 Ouvrir dans HERE WeGo','https://share.here.com/r/mylocation/47.956993,7.297501,Boulangerie%20P%C3%A2tisserie%20Astrid%20et%20Alexandre%20Hadey%20-%2013%20Rue%20de%20la%20Pr%C3%A9vot%C3%A9%2C%20Rouffach?m=b'],['📖 En savoir plus','https://www.tourisme-eguisheim-rouffach.com/FR/Rouffach-f253001819.html']]],
['🚴 Suite du parcours','Après Rouffach, continuer sur le nouveau tracé en direction de Cernay. La journée se termine désormais à Cernay; Aspach-le-Bas n’est plus la ville-étape du Jour 7.'],
['🥐 Solution de secours — Cernay','À l’arrivée, la Pâtisserie Hincker, 22 rue Raymond-Poincaré, est ouverte le lundi de 7 h 30 à 18 h.'],
['🍽️ Repas à proximité','À Cernay, plusieurs boulangeries, commerces et solutions à emporter permettent de préparer facilement le repas du soir.'],
['🛒 Provisions','Faire les provisions à Cernay pour le soir et le départ du lendemain.']
],links:[['GPX - Colmar @ Cernay','https://ridewithgps.com/routes/57036457'],['🥐 Boulangerie-Pâtisserie Hadey — Rouffach (~ km 20)','https://share.here.com/r/mylocation/47.956993,7.297501,Boulangerie%20P%C3%A2tisserie%20Astrid%20et%20Alexandre%20Hadey%20-%2013%20Rue%20de%20la%20Pr%C3%A9vot%C3%A9%2C%20Rouffach?m=b'],['🥐 Pâtisserie Hincker — Cernay','https://share.here.com/r/mylocation/47.807640,7.175367,P%C3%A2tisserie%20Hincker%20-%2022%20Rue%20Raymond%20Poincar%C3%A9%2C%20Cernay?m=b'],['🛒 Souper / provisions — Supermarché Match Cernay','https://share.here.com/r/mylocation/47.806578,7.174281,Supermarch%C3%A9%20Match%20-%2034%20Rue%20Georges%20Risler%2C%20Cernay?m=b']]},
{n:8,date:'Mardi 8 septembre 2026',title:'Cernay → Colombier-Fontaine',spirit:'Quitter l’Alsace, traverser le secteur de Montbéliard et terminer l’étape à Colombier-Fontaine.',facts:[['Distance','69 km'],['Dénivelé positif','261 m'],['Pause pâtisserie','Dannemarie ou Montreux-Château'],['Arrivée','Colombier-Fontaine']],stops:[
['Départ — Cernay','Départ depuis Cernay en suivant le nouveau GPX du Jour 8.'],
['🥐 Pause pâtisserie — Dannemarie','La Meunière, 13 place de l’Hôtel de Ville, est une boulangerie-pâtisserie et salon de thé ouverte le mardi. Elle constitue une halte pratique après environ 25 km.'],
['🥐 Option plus tardive — Montreux-Château','La Fontaine aux Délices, 14 rue du Général-de-Gaulle, se trouve près du km 34,4 du parcours. Compter environ 840 m entre le GPX et la boulangerie. Elle est ouverte le mardi de 6 h 45 à 13 h puis de 16 h à 19 h.'],
['🚴 Vers Montbéliard','Poursuivre le tracé en direction de Montbéliard en restant sur le GPX.'],
['🛒 Souper — Montbéliard','Acheter le souper à l’Intermarché CONTACT, 15 rue du Port. Le magasin est tout près du tracé et évite un détour important avec les vélos.'],
['⏰ Intermarché — horaire du mardi','Ouvert de 8 h 30 à 19 h 30. Faire les achats avant de poursuivre vers Colombier-Fontaine.'],
['🚴 Fin d’étape','Après les courses, reprendre le GPX vers Colombier-Fontaine.'],
['🏁 Arrivée — Colombier-Fontaine','Fin du Jour 8 à Colombier-Fontaine.']
],links:[
['GPX - Cernay @ Colombier-Fontaine','https://ridewithgps.com/routes/57052160'],
['🚲 GPX km 24,5 → La Meunière','https://share.here.com/r/47.635600,7.115580,GPX%20km%2024%2C5/47.631378,7.120134,La%20Meuni%C3%A8re%20-%2013%20Place%20de%20l%E2%80%99H%C3%B4tel%20de%20Ville%2C%20Dannemarie?m=b'],
['🚲 GPX km 34,4 → La Fontaine aux Délices','https://share.here.com/r/47.603520,7.010970,GPX%20km%2034%2C4/47.609193,7.003573,La%20Fontaine%20aux%20D%C3%A9lices%20-%2014%20Rue%20du%20G%C3%A9n%C3%A9ral%20de%20Gaulle%2C%20Montreux-Ch%C3%A2teau?m=b'],
['🛒 Intermarché CONTACT — Montbéliard','https://share.here.com/r/mylocation/47.5036703,6.7922554,Intermarch%C3%A9%20CONTACT%20-%2015%20Rue%20du%20Port%2C%20Montb%C3%A9liard?m=b'],
['📍 Colombier-Fontaine','https://share.here.com/r/mylocation/47.452240,6.690100,Colombier-Fontaine?m=b']
]},
{n:9,date:'Mercredi 9 septembre 2026',title:'Colombier-Fontaine → Roche-lez-Beaupré',spirit:'Suivre la vallée du Doubs vers Baume-les-Dames puis poursuivre jusqu’à Roche-lez-Beaupré, en gardant une pause pâtisserie facile sur ou près du GPX.',facts:[['Distance','71 km'],['Dénivelé positif','585 m'],['Pause pâtisserie','Pays-de-Clerval ou Baume-les-Dames'],['Arrivée','Roche-lez-Beaupré']],stops:[
['Départ — Colombier-Fontaine','Départ depuis Colombier-Fontaine en suivant le nouveau GPX du Jour 9.'],
['🥐 Option 1 — L’Épi d’Or, Pays-de-Clerval','Vers le km 27,6. Boulangerie-pâtisserie au 9 avenue Gaston Renaud, pratiquement sur le GPX (environ 15 à 20 m). Ouverte le mercredi de 6 h à 13 h puis de 16 h à 18 h 30.'],
['🥐 Option km 30–45 — Le Fournil d’Anroz','Vers le km 43,6, au 13 faubourg d’Anroz à Baume-les-Dames. Compter environ 500 m entre le GPX et la boulangerie. Ouverte le mercredi de 6 h à 19 h. C’est la meilleure halte trouvée dans la fenêtre km 30 à 45.'],
['🚴 Vallée du Doubs','Poursuivre ensuite le tracé en direction de Roche-lez-Beaupré.'],
['🏁 Arrivée — Roche-lez-Beaupré','Fin du Jour 9 à Roche-lez-Beaupré.']
],links:[
['GPX - Colombier-Fontaine @ Roche-lez-Beaupré','https://ridewithgps.com/routes/57070393'],
['📍 L’Épi d’Or — HERE WeGo','https://share.here.com/l/47.392701,6.493706,L%27%C3%89pi%20d%27Or%20-%209%20Avenue%20Gaston%20Renaud%2C%20Pays-de-Clerval?z=18'],
['🚲 GPX km 43,6 → Le Fournil d’Anroz','https://share.here.com/r/47.350720,6.373460,GPX%20km%2043%2C6/47.350732,6.366820,Le%20Fournil%20d%27Anroz%20-%2013%20Faubourg%20d%27Anroz%2C%20Baume-les-Dames?m=b'],
['📍 Roche-lez-Beaupré','https://share.here.com/r/mylocation/47.276530,6.115950,Roche-lez-Beaupr%C3%A9?m=b']
]},
{n:10,date:'Jeudi 10 septembre 2026',title:'Roche-lez-Beaupré → Dole',spirit:'Poursuivre vers Dole en suivant la vallée du Doubs et l’EuroVelo 6, avec une halte pâtisserie facile à intégrer au parcours.',facts:[['Distance','≈ 69 km'],['Dénivelé positif','À confirmer'],['Pause pâtisserie','Fraisans ou Ranchot'],['Arrivée','Dole']],stops:[
['Départ — Roche-lez-Beaupré','Départ depuis Roche-lez-Beaupré sur le nouveau tracé du Jour 10 en direction de Dole.'],
['🥐 La Petite Symphonie — Fraisans','Vers le km 44,9. Boulangerie-pâtisserie au 1 place de la Liberté, ouverte le jeudi de 6 h à 13 h. Elle se trouve à environ 900 m du GPX : le bouton HERE WeGo lance donc un véritable itinéraire vélo depuis le point du parcours le plus proche.'],
['🥐 Boulangerie Redoutey — Ranchot','Vers le km 47,6. Boulangerie-pâtisserie au 21 Grande Rue, ouverte le jeudi de 6 h 30 à 13 h puis de 16 h à 19 h. Elle est pratiquement sur la véloroute; le lien ouvre directement sa localisation dans HERE WeGo.'],
['🚴 Vallée du Doubs / EuroVelo 6','L’étape suit en grande partie le Doubs et son corridor cyclable jusqu’à Dole.'],
['🏁 Arrivée — Dole','Fin du nouveau GPX à Dole.'],
['🏡 Hébergement','Privilégier un logement près du centre ou du parcours, avec un endroit sécuritaire pour les deux vélos.'],
['🍽️ Repas et provisions','Dole offre plusieurs commerces, traiteurs et restaurants dans le centre pour le souper et les provisions du lendemain.']
],links:[
['GPX - Roche-lez-Beaupré @ Dole','https://ridewithgps.com/routes/57084400'],
['🚲 GPX km 44,9 → La Petite Symphonie','https://share.here.com/r/47.156660,5.756750,GPX%20km%2044%2C9/47.149340,5.762000,La%20Petite%20Symphonie%20-%201%20Place%20de%20la%20Libert%C3%A9%2C%20Fraisans?m=b'],
['📍 Boulangerie Redoutey — HERE WeGo','https://share.here.com/l/47.149010,5.724490,Boulangerie%20Redoutey%20-%2021%20Grande%20Rue%2C%20Ranchot?z=18'],
['📍 Arrivée — Dole','https://share.here.com/l/47.095140,5.497100,Dole?z=15']
]},
{n:11,date:'Vendredi 11 septembre 2026',title:'Dole → Marsannay-la-Côte',spirit:'Une étape plus courte vers la Côte de Nuits, avec une pause pâtisserie presque exactement à mi-parcours à Brazey-en-Plaine.',facts:[['Distance','≈ 54 km'],['Dénivelé positif','386 m'],['Pause pâtisserie','Petit Crouton — Brazey-en-Plaine (~ km 28,3)'],['Arrivée','3 rue Neuve, Marsannay-la-Côte']],stops:[
['Départ — Dole','Départ de Dole sur le GPX corrigé du Jour 11 en direction de Marsannay-la-Côte. Le nouveau tracé RideWithGPS mesure environ 54,1 km.'],
['🥐 Pause pâtisserie — Petit Crouton, Brazey-en-Plaine','Vers le km 28,3, donc pratiquement à mi-parcours. Boulangerie-pâtisserie au 4 route de Dijon, 21470 Brazey-en-Plaine. Elle est ouverte le vendredi de 6 h à 19 h. Le centre de Brazey se trouve à environ 650 à 700 m du point le plus proche du GPX : c’est une petite déviation raisonnable pour la pause.'],
['🚴 Reprise vers Marsannay-la-Côte','Après Brazey-en-Plaine, reprendre le GPX corrigé et poursuivre vers Marsannay-la-Côte.'],
['🏡 Arrivée — 3 rue Neuve','Arrivée au 3 rue Neuve, 21160 Marsannay-la-Côte. Cet hébergement est prévu pour trois nuits : vendredi 11, samedi 12 et dimanche 13 septembre.'],
['🍽️ Repas et provisions','Pour le soir, plusieurs commerces et restaurants sont accessibles à Marsannay-la-Côte; les grandes surfaces se trouvent dans la zone commerciale au nord-est du bourg.'],
['⭐ Repère','Marsannay-la-Côte est votre base pour les visites des vignobles le samedi et pour Dijon le dimanche.']
],links:[
['GPX RideWithGPS — Dole → Marsannay-la-Côte','https://ridewithgps.com/routes/57098017'],
['🥐 Petit Crouton — HERE WeGo','https://wego.here.com/search/Petit%20Crouton%2C%204%20Route%20de%20Dijon%2C%2021470%20Brazey-en-Plaine'],
['🏡 Hébergement — 3 rue Neuve','https://wego.here.com/search/3%20Rue%20Neuve%2C%2021160%20Marsannay-la-C%C3%B4te'],
['📍 Centre de Marsannay-la-Côte','https://wego.here.com/search/Marsannay-la-C%C3%B4te']
]},
{n:12,date:'Samedi 12 septembre 2026',title:'Découverte de Dijon',spirit:'Prendre le temps de découvrir Dijon à pied, en gardant la liberté de choisir les activités selon votre énergie et la météo.',facts:[['Type','Journée de visite'],['Déplacement','Marsannay-la-Côte → Dijon : à vélo ou en Uber, puis à pied'],['Rythme','Libre et sans horaire rigide'],['Hébergement','Deuxième nuit à Marsannay-la-Côte']],stops:[
['Transport vers Dijon','Commencer la journée par le déplacement de Marsannay-la-Côte vers le centre de Dijon. Deux options restent ouvertes : faire le trajet à vélo ou prendre un Uber. Vous déciderez sur place selon la météo, votre énergie et la façon dont vous souhaitez organiser le retour.'],
['Parcours de la Chouette','Ce parcours pédestre suit de petites chouettes de bronze incrustées dans le sol et traverse les rues anciennes, les hôtels particuliers, les places et les principaux monuments du centre historique.<br><strong>Pourquoi le faire :</strong> c’est la meilleure façon de prendre contact avec Dijon sans horaire rigide, tout en reliant naturellement plusieurs autres activités de la journée.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Parcours%20de%20la%20Chouette%20Dijon']]],
['Palais des ducs et des États de Bourgogne','Au cœur de la place de la Libération, ce vaste ensemble rappelle l’époque où les ducs de Bourgogne dirigeaient l’un des États les plus puissants d’Europe. Il abrite aujourd’hui notamment l’hôtel de ville et le musée des Beaux-Arts.<br><strong>Pourquoi le voir :</strong> ses façades, ses cours et la place permettent de comprendre immédiatement l’importance historique de Dijon.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Palais%20des%20Ducs%20et%20des%20Etats%20de%20Bourgogne%20Dijon']]],
['Tour Philippe le Bon','Cette tour de 46 mètres domine le palais des ducs et offre une vue panoramique sur les toits du centre historique et les environs de Dijon.<br><strong>Pourquoi la faire :</strong> elle donne une excellente vue d’ensemble de la ville. Vérifier l’horaire et réserver, car l’accès se fait habituellement dans le cadre d’une visite organisée.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Tour%20Philippe%20le%20Bon%20Dijon']]],
['Halles centrales et marché','Les Halles occupent un bâtiment emblématique du centre-ville. Les étals mettent en valeur les produits frais et les spécialités de Bourgogne : fromages, charcuteries, fruits, légumes, pains et plats préparés.<br><strong>Pourquoi y aller :</strong> c’est une belle occasion de découvrir les produits locaux et d’acheter un repas simple ou des provisions. Vérifier les jours et heures du marché.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Halles%20Centrales%20Dijon']]],
['Atelier de fabrication de moutarde','Un moutardier présente les ingrédients et les étapes de fabrication, puis vous préparez votre propre moutarde et repartez avec votre création. L’activité nécessite normalement une réservation.<br><strong>Pourquoi le faire :</strong> c’est une expérience typiquement dijonnaise, concrète et amusante, qui va au-delà d’une simple visite de boutique.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Atelier%20de%20creation%20de%20moutarde%20Fallot%20Dijon']]],
['Musée des Beaux-Arts de Dijon','Installé dans le palais des ducs, le musée couvre plusieurs siècles d’histoire de l’art et présente notamment les célèbres tombeaux des ducs de Bourgogne. Les collections permanentes sont gratuites.<br><strong>Pourquoi le visiter :</strong> son emplacement permet de l’ajouter facilement, même pour une visite courte. C’est aussi une excellente option en cas de pluie ou pour une activité plus calme.',[['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Musee%20des%20Beaux-Arts%20Dijon']]],
['Choix sur place','L’atelier de moutarde et le musée restent tous les deux au programme. Vous pourrez décider sur place d’en faire un seul ou les deux, selon votre énergie, les disponibilités et la météo.']
],links:[['🚶 Ouvrir l’itinéraire complet à pied dans HERE WeGo','https://wego.here.com/directions/mix/86%20Rue%20Monge%2C%2021000%20Dijon%2C%20France/Mus%C3%A9e%20des%20Beaux-Arts%20de%20Dijon%2C%20Place%20des%20Ducs%20de%20Bourgogne%2C%2021000%20Dijon%2C%20France']]},
{n:13,date:'Dimanche 13 septembre 2026',title:'Boucle dans les vignobles',spirit:'Profiter d’une journée légère, sans bagages, pour rouler dans les vignobles de la Côte de Nuits et choisir librement une ou deux visites de domaines.',facts:[['Distance','25 km'],['Dénivelé positif','231 m'],['Type','Boucle à vélo sans bagages'],['Visites','Un ou deux domaines, à décider sur place']],stops:[
['Départ — Marsannay-la-Côte','Partir de l’hébergement avec les vélos non chargés et rejoindre les petites routes viticoles en direction de Fixin, Gevrey-Chambertin et Morey-Saint-Denis. La journée demeure volontairement souple, sans horaire imposé.'],
['Fixin et les vignobles de la Côte de Nuits','Le circuit traverse les paysages viticoles entre Marsannay-la-Côte et Gevrey-Chambertin. Prendre le temps de profiter des villages, des parcelles et des points de vue, sans objectif de vitesse.'],
['Domaine René Leclerc — Gevrey-Chambertin','Première visite possible de la journée. Ce domaine familial produit notamment plusieurs Gevrey-Chambertin, premiers crus et grands crus. La visite et la dégustation dépendent des disponibilités du domaine.<br><strong>Décision sur place :</strong> faire cette visite, poursuivre vers Morey-Saint-Denis, ou conserver l’énergie pour le second domaine.',[['🌐 Site du domaine','https://domainereneleclerc.com/'],['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Domaine%20Rene%20Leclerc%20Gevrey-Chambertin']]],
['Domaine des Beaumont — Morey-Saint-Denis','Deuxième visite possible. Cette petite exploitation familiale travaille des parcelles à Morey-Saint-Denis, Gevrey-Chambertin et Chambolle-Musigny. La visite permettrait de découvrir un domaine plus intime et une gamme représentative de plusieurs villages de la Côte de Nuits.<br><strong>Décision sur place :</strong> visiter ce domaine seul ou l’ajouter au Domaine René Leclerc, selon les disponibilités et votre envie.',[['ℹ️ Information sur le domaine','https://www.gevreynuitstourisme.com/ddata/domaine-des-beaumont/'],['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Domaine%20des%20Beaumont%20Morey-Saint-Denis']]],
['Retour — Marsannay-la-Côte','Revenir tranquillement à Marsannay-la-Côte en complétant la boucle. Comme vous n’aurez pas les bagages, vous pourrez ajuster le rythme et les arrêts selon la durée des visites.'],
['Choix sur place','Aucun horaire n’est fixé. Vous déciderez le jour même de visiter le Domaine René Leclerc, le Domaine des Beaumont, ou les deux. Il est prudent de vérifier les disponibilités avant d’entrer dans les domaines.']
],links:[
['GPX - Marsannay-la-Côte @ Marsannay-la-Côte','https://ridewithgps.com/routes/56269077'],
['📍 Domaine René Leclerc','https://wego.here.com/search/Domaine%20Rene%20Leclerc%20Gevrey-Chambertin'],
['📍 Domaine des Beaumont','https://wego.here.com/search/Domaine%20des%20Beaumont%20Morey-Saint-Denis']
]},
{n:14,date:'Lundi 14 septembre 2026',title:'Marsannay-la-Côte → Chagny',spirit:'Reprendre la route à travers les grands vignobles de Bourgogne et réserver l’arrêt principal de la journée à Meursault.',facts:[['Distance','70 km'],['Dénivelé positif','438 m'],['Arrêt principal','Meursault'],['Hébergement','À confirmer — Chagny']],stops:[
['Départ — Marsannay-la-Côte','Quitter Marsannay-la-Côte après trois nuitées et reprendre la route avec les vélos chargés. Le parcours suit la Côte de Nuits puis la Côte de Beaune, au cœur de la Route des Grands Crus.'],
['Clos de Vougeot — vers le km 13,5','Passage tout près du château. Prévoir seulement un arrêt photo ou une courte pause afin de garder du temps pour Meursault, qui demeure la visite principale de la journée.'],
['Nuits-Saint-Georges — vers le km 19','Premier véritable arrêt de la journée : boulangerie ou pâtisserie, remplissage des bouteilles et ravitaillement au besoin.',[['🥐 Pâtisserie Olivier Bourau — HERE WeGo','https://wego.here.com/search/Patisserie%20Olivier%20Bourau%2028%20Grande%20Rue%20Nuits-Saint-Georges'],['🥐 Autres boulangeries à proximité','https://wego.here.com/search/boulangerie%20patisserie%20Nuits-Saint-Georges']]],
['Beaune — vers le km 42','Le parcours passe près de Beaune sans imposer une longue visite du centre. La ville constitue toutefois une excellente solution de repli pour dîner, acheter un repas à emporter ou utiliser les services.'],
['Pommard et Volnay — km 46 à 47','Traverser tranquillement les vignobles de Pommard et de Volnay. Profiter des paysages et des villages, avec quelques arrêts spontanés pour les photos.'],
['Meursault — vers le km 51','Arrêt principal de la journée. Comme vous aimez particulièrement les vins de Meursault, prévoir le dîner ainsi qu’une visite ou une dégustation dans un domaine. Le Château de Meursault se trouve à environ 400 mètres du tracé. Selon l’heure d’arrivée et les disponibilités, choisir une visite complète ou demander une dégustation plus courte et modérée avant de reprendre les vélos.',[['🌐 Château de Meursault','https://www.chateau-meursault.com/'],['📍 Ouvrir dans HERE WeGo','https://wego.here.com/search/Chateau%20de%20Meursault']]],
['Puligny-Montrachet — vers le km 55','Traverser ce village réputé pour ses grands vins blancs. Le passage est surtout panoramique et ne nécessite pas une autre visite organisée.'],
['Santenay — vers le km 64','Dernière halte possible avant Chagny : courte pause, photos et ravitaillement rapide au besoin.'],
['Arrivée — Chagny','Terminer l’étape à Chagny, ville pratique pour les cyclistes avec commerces, restaurants et accès facile au canal du Centre pour la suite du voyage. Vérifier l’accès à l’hébergement et le rangement sécuritaire des vélos.']
],links:[
['GPX - Marsannay-la-Côte @ Chagny','https://ridewithgps.com/routes/56269293'],
['📍 Château de Meursault','https://wego.here.com/search/Chateau%20de%20Meursault'],
['🍽️ Restaurants — Chagny','https://wego.here.com/search/restaurants%20Chagny'],
['🛒 Épiceries — Chagny','https://wego.here.com/search/epicerie%20supermarche%20Chagny']
]},
{n:15,date:'Mardi 15 septembre 2026',title:'Chagny → Tournus',spirit:'Profiter d’une étape plus douce le long de la Saône, avec une vraie pause gourmande à Chalon-sur-Saône.',facts:[['Distance','53 km'],['Dénivelé positif','173 m'],['Pause pâtisserie','Chalon-sur-Saône'],['Hébergement','À confirmer — Tournus']],stops:[
['Départ — Chagny','Quitter Chagny et rejoindre progressivement la vallée de la Saône. La journée est volontairement plus courte afin de garder un rythme agréable après l’étape viticole de la veille.'],
['Chalon-sur-Saône — vers le km 21','Première grande halte après environ une à deux heures de vélo. Profiter du centre pour une pâtisserie, remplir les bouteilles et faire quelques achats au besoin.',[['🥐 Allex — pâtissier, chocolatier et glacier','https://wego.here.com/search/Allex%20Patissier%2011%20Place%20de%20l%27Hotel%20de%20Ville%20Chalon-sur-Saone'],['🥐 La Tartelière — HERE WeGo','https://wego.here.com/search/La%20Tarteliere%204%20Rue%20Saint%20Vincent%20Chalon-sur-Saone']]],
['Voie Bleue le long de la Saône','Après Chalon-sur-Saône, suivre l’itinéraire cyclable en direction du sud. Le parcours est généralement roulant et permet de profiter du paysage sans difficulté importante.'],
['Pause repas en route','Selon l’heure et l’appétit, acheter un sandwich ou un repas à emporter à Chalon-sur-Saône, ou poursuivre jusqu’à Tournus pour dîner après l’arrivée.'],
['Arrivée — Tournus','Ranger les vélos puis profiter du centre ancien. Tournus offre des restaurants, des commerces et plusieurs possibilités de ravitaillement pour le souper et le lendemain.']
],links:[
['GPX - Chagny @ Tournus','https://ridewithgps.com/routes/56273151'],
['🥐 Pâtisseries — Chalon-sur-Saône','https://wego.here.com/search/patisserie%20boulangerie%20Chalon-sur-Saone'],
['🍽️ Restaurants — Tournus','https://wego.here.com/search/restaurants%20Tournus'],
['🛒 Épiceries — Tournus','https://wego.here.com/search/epicerie%20supermarche%20Tournus']
]},
{n:16,date:'Mercredi 16 septembre 2026',title:'Tournus → Belleville-en-Beaujolais',spirit:'Poursuivre tranquillement le long de la Saône, faire une vraie pause à Mâcon et rejoindre une ville-étape bien équipée aux portes du Beaujolais.',facts:[['Distance','62 km'],['Dénivelé positif','324 m'],['Pause pâtisserie','Mâcon — vers le km 33'],['Hébergement','À confirmer — Belleville-en-Beaujolais']],stops:[
['Départ — Tournus','Quitter Tournus et reprendre la Voie Bleue vers le sud. Le parcours longe la Saône sur une étape généralement roulante, avec les vélos chargés.'],
['Mâcon — vers le km 33','Après environ une heure et demie à deux heures de vélo, faire la principale pause gourmande de la journée dans le centre de Mâcon. Profiter de cet arrêt pour une pâtisserie, remplir les bouteilles et acheter un sandwich ou quelques provisions au besoin.',[['🥐 Pâtisseries et boulangeries — Mâcon','https://wego.here.com/search/patisserie%20boulangerie%20centre%20Macon'],['📍 Centre de Mâcon','https://wego.here.com/search/centre%20ville%20Macon']]],
['Voie Bleue et vallée de la Saône','Après Mâcon, poursuivre vers le sud le long de la Saône. Garder un rythme régulier et profiter des haltes au bord de l’eau sans multiplier les grands détours.'],
['Thoissey et secteur de Saint-Didier-sur-Chalaronne','Ce secteur constitue une possibilité de pause plus tardive pour l’eau, les toilettes ou un ravitaillement rapide avant les derniers kilomètres.'],
['Arrivée — Belleville-en-Beaujolais','Quitter légèrement le tracé principal pour rejoindre l’hébergement à Belleville-en-Beaujolais. La ville offre davantage de choix pour dormir, souper et faire les provisions que les petites communes voisines. Vérifier le rangement sécuritaire des deux vélos.']
],links:[
['GPX - Tournus @ Belleville-en-Beaujolais','https://ridewithgps.com/routes/56273559'],
['🥐 Pâtisseries — Mâcon','https://wego.here.com/search/patisserie%20boulangerie%20centre%20Macon'],
['🍽️ Restaurants — Belleville-en-Beaujolais','https://wego.here.com/search/restaurants%20Belleville-en-Beaujolais'],
['🛒 Épiceries — Belleville-en-Beaujolais','https://wego.here.com/search/epicerie%20supermarche%20Belleville-en-Beaujolais'],
['🏡 Hébergements — Belleville-en-Beaujolais','https://wego.here.com/search/hebergement%20Belleville-en-Beaujolais']
]},
{n:17,date:'Jeudi 17 septembre 2026',title:'Belleville-en-Beaujolais → Givors',spirit:'Traverser l’agglomération lyonnaise sans s’y arrêter et contourner entièrement le tronçon déconseillé de la ViaRhôna.',facts:[['Distance','76 km'],['Dénivelé positif','438 m'],['Pause pâtisserie','Neuville-sur-Saône — vers le km 35'],['Hébergement','À confirmer — Givors']],stops:[
['Départ — Belleville-en-Beaujolais','Quitter Belleville-en-Beaujolais et reprendre la vallée de la Saône vers le sud. Cette journée est plus longue que les deux précédentes; partir suffisamment tôt et conserver un rythme régulier.'],
['Trévoux — vers le km 24','Traverser le secteur de Trévoux sans grand détour. Cette ancienne ville parlementaire constitue une première possibilité de courte pause pour l’eau ou les toilettes.'],
['Neuville-sur-Saône — vers le km 35','Faire ici la principale pause pâtisserie de la journée, après environ une heure et demie à deux heures de vélo. Profiter de l’arrêt pour remplir les bouteilles et acheter un sandwich ou des provisions pour la suite.',[['🥐 Pâtisseries et boulangeries — Neuville-sur-Saône','https://wego.here.com/search/patisserie%20boulangerie%20Neuville-sur-Saone'],['📍 Centre de Neuville-sur-Saône','https://wego.here.com/search/centre%20Neuville-sur-Saone']]],
['Traversée de Lyon — sans arrêt touristique','Suivre le tracé à travers l’agglomération lyonnaise sans programmer de visite, puisque vous aurez déjà séjourné à Lyon au début du voyage. Rester particulièrement attentifs aux intersections, aux piétons et à la circulation urbaine.'],
['Contournement sécuritaire par l’ouest','À partir d’Oullins–Pierre-Bénite, le GPX quitte le tracé officiel problématique et passe par Saint-Genis-Laval, Brignais, Vourles, Millery et Grigny-sur-Rhône. Cette variante évite complètement le mauvais tronçon de la ViaRhôna par Vernaison, Ternay et Chasse-sur-Rhône. Ne pas suivre les panneaux ViaRhôna s’ils contredisent le GPX dans ce secteur.'],
['L’Atelier Vélo — secteur sud de Lyon','Le GPX comprend un point de repère pour L’Atelier Vélo. Le conserver comme solution de dépannage éventuelle, sans prévoir un arrêt systématique.'],
['Arrivée — Givors','Rejoindre Givors par Grigny-sur-Rhône. La ville constitue une étape pratique au-delà de Lyon, avec gare, commerces et services. Vérifier à l’hébergement qu’un rangement sécuritaire est prévu pour les deux vélos.']
],links:[
['GPX - Belleville-en-Beaujolais @ Givors','https://ridewithgps.com/routes/56281487'],
['🥐 Pâtisseries — Neuville-sur-Saône','https://wego.here.com/search/patisserie%20boulangerie%20Neuville-sur-Saone'],
['🍽️ Restaurants — Givors','https://wego.here.com/search/restaurants%20Givors'],
['🛒 Épiceries — Givors','https://wego.here.com/search/epicerie%20supermarche%20Givors'],
['🏡 Hébergements — Givors','https://wego.here.com/search/hebergement%20Givors']
]},
{n:18,date:'Vendredi 18 septembre 2026',title:'Givors → Tain-l’Hermitage',spirit:'Quitter l’agglomération lyonnaise, retrouver progressivement les paysages du Rhône et terminer la journée au pied des coteaux de l’Hermitage.',facts:[['Distance','78 km'],['Dénivelé positif','366 m'],['Parcours','RideWithGPS 56790082'],['Arrivée','Tain-l’Hermitage']],stops:[
['Départ — Givors','Quitter Givors en suivant le parcours RideWithGPS prévu pour la journée.'],
['Vallée du Rhône','Progression vers le sud avec plusieurs secteurs aménagés le long du Rhône. Rester attentifs aux raccordements urbains et aux traversées de voirie lorsque l’itinéraire quitte temporairement les voies cyclables.'],
['Pause en cours de route','Prévoir une pause pâtisserie ou boulangerie après environ 1 h 30 à 2 h de vélo, selon l’heure de départ et les commerces ouverts sur le parcours.'],
['Approche de Tain-l’Hermitage','L’arrivée se fait dans le secteur viticole de Tain-l’Hermitage, face à Tournon-sur-Rhône.'],
['Arrivée — Tain-l’Hermitage','Installation à l’hébergement. Ce secteur est un excellent candidat pour deux nuits afin de consacrer une journée aux vignobles, au Domaine du Colombier et à la Cité du Chocolat Valrhona.']
],links:[
['GPX - Givors @ Tain-l’Hermitage','https://ridewithgps.com/routes/56790082'],
['🍽️ Restaurants — Tain-l’Hermitage','https://wego.here.com/search/restaurants%20Tain-l%27Hermitage'],
['🛒 Épiceries — Tain-l’Hermitage','https://wego.here.com/search/epicerie%20supermarche%20Tain-l%27Hermitage'],
['🏡 Hébergements — Tain-l’Hermitage','https://wego.here.com/search/hebergement%20Tain-l%27Hermitage']
]},
{n:19,date:'Samedi 19 septembre 2026',title:'Tain-l’Hermitage — vignobles et chocolat',spirit:'Profiter d’une journée sans bagages pour découvrir Tain, le coteau de l’Hermitage, rencontrer la famille Viale et terminer par Valrhona.',facts:[['Nuit','2e nuit à Tain-l’Hermitage'],['Rythme','Journée découverte'],['Vélo','Sans bagages'],['Trajet','À préparer']],stops:[
['1. Marché de Tain-l’Hermitage','Commencer la matinée au marché du samedi, place du Taurobole. Acheter de quoi préparer le souper puis revenir déposer les provisions à l’Airbnb avant de repartir.<br><strong>Horaire actuel :</strong> samedi de 7 h à 12 h.',[['📍 HERE WeGo','https://wego.here.com/search/Place%20du%20Taurobole%2026600%20Tain-l%27Hermitage'],['ℹ️ Marché — Ville de Tain','https://www.ville-tain.fr/fr/mon-quotidien/marche-et-commerces/marche-hebdomadaire/']]],
['2. Chapelle Saint-Christophe','Monter sur le coteau de l’Hermitage jusqu’à la chapelle Saint-Christophe. Le site domine Tain, le Rhône et les vignobles et constitue un très beau point de vue avant de poursuivre la boucle.',[['📍 HERE WeGo','https://wego.here.com/search/Chapelle%20Saint-Christophe%20Tain-l%27Hermitage'],['ℹ️ Patrimoine — Ville de Tain','https://www.ville-tain.fr/fr/ma-ville/histoire/patrimoine/']]],
['3. Domaine du Colombier — Florent et David Viale','Visite chez la famille Viale, recommandée par Simon. Le domaine se trouve au 2 route de Chantemerle à Tain-l’Hermitage. La visite se fait sur rendez-vous; l’heure sera ajustée lorsque le contact avec le domaine sera confirmé.',[['📍 HERE WeGo','https://wego.here.com/search/Domaine%20du%20Colombier%202%20Route%20de%20Chantemerle%2026600%20Tain-l%27Hermitage'],['🍷 Fiche du domaine','https://www.crozes-hermitage-vin.fr/fr/caves-maisons/domaine-du-colombier']]],
['4. Cité du Chocolat Valrhona','Terminer la journée par la Cité du Chocolat. Prévoir environ 1 h 30 à 2 h. Réservation recommandée; vérifier également la programmation du samedi 19 septembre avant le voyage.',[['📍 HERE WeGo','https://wego.here.com/search/Cite%20du%20Chocolat%20Valrhona%2012%20Avenue%20du%20President%20Roosevelt%2026600%20Tain-l%27Hermitage'],['🎟️ Cité du Chocolat Valrhona','https://www.citeduchocolat.com/fr/preparer-sa-visite/informations-pratiques']]],
['Activité supplémentaire — Cave de Tain','À garder seulement si le temps et l’envie le permettent. Elle n’est pas intégrée au programme principal de la journée.',[['📍 HERE WeGo','https://wego.here.com/search/Cave%20de%20Tain%2022%20Route%20de%20Larnage%2026600%20Tain-l%27Hermitage'],['🍷 Cave de Tain','https://www.cavedetain.com/']]]
]},
{n:20,date:'Dimanche 20 septembre 2026',title:'Tain-l’Hermitage → Montélimar',spirit:'Poursuivre vers le sud jusqu’à Montélimar en gardant un rythme régulier sur cette étape plus longue, avec une pause pâtisserie à Valence.',facts:[['Distance','82 km'],['Dénivelé positif','396 m'],['Pause pâtisserie','Valence — vers le km 21'],['Arrivée','Montélimar']],stops:[
['Départ — Tain-l’Hermitage','Quitter Tain après deux nuits sur place et reprendre l’itinéraire vers le sud en direction de Valence puis de Montélimar.'],
['Valence — vers le km 21','Après environ 1 h à 1 h 30 de vélo, faire ici la principale pause pâtisserie-boulangerie de la journée. Profiter de l’arrêt pour remplir les bouteilles et acheter au besoin quelques provisions.',[['🥐 Pâtisseries et boulangeries — Valence','https://wego.here.com/search/patisserie%20boulangerie%20Valence'],['📍 Centre de Valence','https://wego.here.com/search/centre%20Valence%20Drome']]],
['Poursuite vers Montélimar','Après Valence, continuer vers le sud en suivant le parcours prévu. Cette deuxième partie est plus longue : prévoir eau et ravitaillement avant de quitter les principaux secteurs commerçants.'],
['Arrivée — Montélimar','Fin de l’étape après 82 km. S’installer, sécuriser les deux vélos et faire les provisions pour le lendemain.']
],links:[
['GPX - Tain-l’Hermitage @ Montélimar','https://ridewithgps.com/routes/56830705'],
['🚴 ViaRhôna — secteur Valence','https://www.viarhona.com/itineraire/tournon-sur-rhone-glun-a-bourg-les-valence-valence'],
['🍽️ Restaurants — Montélimar','https://wego.here.com/search/restaurants%20Montelimar'],
['🛒 Épiceries — Montélimar','https://wego.here.com/search/epicerie%20supermarche%20Montelimar'],
['🏡 Hébergements — Montélimar','https://wego.here.com/search/hebergement%20Montelimar']
]},
{n:21,date:'Lundi 21 septembre 2026',title:'Montélimar → Orange',spirit:'Poursuivre vers le sud avec une étape plus courte et une vraie pause pâtisserie en route avant l’arrivée à Orange.',facts:[['Distance','63 km'],['Dénivelé positif','271 m'],['Pause pâtisserie','Pierrelatte — vers le km 25'],['Arrivée','Orange']],stops:[
['Départ — Montélimar','Quitter Montélimar et reprendre l’itinéraire vers le sud en suivant le GPX du Jour 21.'],
['🥐 Pierrelatte — vers le km 25','Après environ 1 h 30 à 2 h de vélo, faire la pause pâtisserie-boulangerie à Pierrelatte. C’est le bon moment pour manger, remplir les bouteilles et prendre au besoin une collation pour la suite.',[['🥐 Pâtisseries et boulangeries — Pierrelatte','https://wego.here.com/search/patisserie%20boulangerie%20Pierrelatte'],['📍 Centre de Pierrelatte','https://wego.here.com/search/centre%20Pierrelatte']]],
['Reprise vers Orange','Après Pierrelatte, poursuivre vers le sud en gardant un rythme confortable. Il reste environ 38 km jusqu’à Orange.'],
['Arrivée — Orange','Fin de l’étape à Orange. S’installer, sécuriser les deux vélos et profiter du reste de la journée pour les provisions et la préparation de l’étape suivante.']
],links:[
['GPX - Montélimar @ Orange','https://ridewithgps.com/routes/56876673'],
['🥐 Pâtisseries — Pierrelatte','https://wego.here.com/search/patisserie%20boulangerie%20Pierrelatte'],
['🍽️ Restaurants — Orange','https://wego.here.com/search/restaurants%20Orange%20Vaucluse'],
['🛒 Épiceries — Orange','https://wego.here.com/search/epicerie%20supermarche%20Orange%20Vaucluse'],
['🏡 Hébergements — Orange','https://wego.here.com/search/hebergement%20Orange%20Vaucluse']
]},
{n:22,date:'Mardi 22 septembre 2026',title:'Orange → Avignon',spirit:'Profiter d’une étape courte pour traverser Châteauneuf-du-Pape, découvrir ses vignobles et rejoindre Avignon sans se presser.',facts:[['Distance','37 km'],['Dénivelé positif','236 m'],['Point fort','Châteauneuf-du-Pape'],['Arrivée','Avignon']],stops:[
['Départ — Orange','Quitter Orange en direction de Châteauneuf-du-Pape en suivant le parcours prévu.'],
['Châteauneuf-du-Pape','Prendre le temps de traverser le village et de profiter des paysages viticoles avant de poursuivre vers Avignon.'],
['Domaine Roger Sabon','Visite prévue au Domaine Roger Sabon. Confirmer l’heure du rendez-vous avant le départ et prévoir une dégustation modérée avant de reprendre les vélos.',[['🍷 Domaine Roger Sabon','https://wego.here.com/search/Domaine%20Roger%20Sabon%20Chateauneuf-du-Pape']]],
['Arrivée — Avignon','Rejoindre Avignon, s’installer et sécuriser les vélos. Profiter ensuite du reste de la journée pour une première promenade dans l’intra-muros.']
],links:[['GPX - Orange @ Avignon','https://ridewithgps.com/routes/56885622'],['📍 Châteauneuf-du-Pape','https://wego.here.com/search/Chateauneuf-du-Pape'],['📍 Avignon centre','https://wego.here.com/search/Avignon%20centre']]},
...Array.from({length:5},(_,i)=>({n:i+23,date:`${i+23} septembre 2026`,title:i===4?'Arrivée à Sète':'Étape vélo à préciser',spirit:i===4?'Atteindre la Méditerranée et savourer le chemin parcouru.':'Cette étape sera complétée lorsque le découpage définitif sera confirmé.',pending:i!==4,facts:[['Statut',i===4?'Arrivée prévue':'À compléter'],['Parcours','Voir RideWithGPS']],stops:[['Préparation','Cette journée sera détaillée lorsque le découpage définitif des étapes sera confirmé.']]}))
];
function route(){const id=(location.hash||'#accueil').slice(1).split('?')[0];document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));(document.getElementById(id)||document.getElementById('accueil')).classList.add('active');window.scrollTo(0,0)}
function renderDays(){dayList.innerHTML=days.map(d=>`<div class="dayitem ${d.pending?'pending':''}" data-day="${d.n}"><div class="daynum">${d.n}</div><div><b>${d.title}</b><small>${d.date}${d.pending?' · à compléter':''}</small></div></div>`).join('');dayList.onclick=e=>{const x=e.target.closest('[data-day]');if(x){renderDay(+x.dataset.day);location.hash='day'}}}
function renderDay(n){const d=days.find(x=>x.n===n);const isRide=d.facts&&d.facts.some(f=>f[0]==='Distance');const shortDate=d.date.replace(/^(Lundi|Mardi|Mercredi|Jeudi|Vendredi|Samedi|Dimanche)\s+/,'').replace(/\s+2026$/,'');dayContent.innerHTML=`${isRide?`<p class="eyebrow">${shortDate}</p><h1>${shortDate} — ${d.title}</h1>`:`<p class="eyebrow">JOUR ${d.n}</p><h1>${d.title}</h1><p class="muted">${d.date}</p>`}${d.pending?'<div class="panel warning"><b>Étape provisoire</b><p>Le découpage, la distance et l’hébergement restent à confirmer.</p></div>':''}<div class="spirit"><small>L’ESPRIT DE LA JOURNÉE</small><strong>${d.spirit}</strong></div><div class="facts">${d.facts.map(f=>`<div class="fact"><small>${f[0]}</small><b>${f[1]}</b></div>`).join('')}</div><h2>Programme</h2><div class="timeline">${d.stops.map(s=>`<div class="stop"><b>${s[0]}</b><p>${s[1]}</p>${s[2]?`<div class="activity-links">${s[2].map(l=>`<a target="_blank" rel="noopener" href="${l[1]}">${l[0]}</a>`).join('')}</div>`:''}</div>`).join('')}</div>${d.actions?`<div class="daylinks">${d.actions.map(a=>`<button class="btn route-action" data-action="${a[1]}" data-file="${a[2]}">${a[0]}</button>`).join('')}</div>`:''}${d.links?`<div class="daylinks">${d.links.map(l=>`<a class="btn" target="_blank" rel="noopener" href="${l[1]}">${l[0]}</a>`).join('')}</div>`:''}`}

document.addEventListener('click',e=>{
});

function loadNotes(){const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');notes.innerHTML=a.map((n,i)=>`<div class="noteitem"><button data-del="${i}">Supprimer</button><b>${escapeHtml(n.t)}</b><p>${escapeHtml(n.x).replace(/\n/g,'<br>')}</p></div>`).join('')||'<p class="muted">Aucune note enregistrée.</p>'}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
saveNote.onclick=()=>{if(!noteText.value.trim())return;const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');a.unshift({t:noteTitle.value.trim()||new Date().toLocaleDateString('fr-CA'),x:noteText.value.trim()});localStorage.setItem('france2026notes',JSON.stringify(a));noteTitle.value=noteText.value='';loadNotes()};notes.onclick=e=>{if(e.target.dataset.del!==undefined){const a=JSON.parse(localStorage.getItem('france2026notes')||'[]');a.splice(+e.target.dataset.del,1);localStorage.setItem('france2026notes',JSON.stringify(a));loadNotes()}};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);window.addEventListener('hashchange',route);renderDays();loadNotes();route();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=11.0',{updateViaCache:'none'}).then(r=>r.update());
